name: Deploy to Production

on:
  push:
    branches: [ main ]
env:
  IMAGE_NAME: xidp/info-manager

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: DockerHub
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          push: true
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop info-manager
            docker rm info-manager
            docker pull xidp/info-manager:latest
            docker run -d --name info-manager --restart always -p 9528:9528 -v /opt/xidp/:/opt/xidp/ xidp/info-manager:latest